language: android
dist: trusty
jdk: openjdk8

before_install:
- chmod +x code/gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- yes | sdkmanager --update

android:
  components:
  - build-tools-29.0.3
  - android-29
  licenses:
  - android-sdk-license-.+

before_script: cd code

script:
  - ./gradlew clean
  - ./gradlew assembleDebug
  - ./gradlew lintDebug
  - ./gradlew testDebug
  - ./gradlew sonarqubeDebug

addons:
  sonarcloud:
    organization: "arx-vestibulum"
    token:
      secure: "FLVDzhsf5DSyvV1jUyqVOHTDcuEcMJY6WtnbbBL9/KiLbDrZCRR5ExFp5NKZTDrixyr5f1Izs2jwz5kjgTYeTiUFVCWARR+zvhCT2H1DyjPrxT6cnZxGNqxU+pCiLi5QxcDy3NH7qVwAFvvMNET9hmJqciSNc96lwM9lnaJAbxrpFN05fXeimlMfAMjPxoJM0SdPbHZLt+hmgoGH/PgLjroOFl7CfF09z+5sKqWqblS38BKHKOAHxsGE+jQp89i4YnUnr9mVpoz+4atRmpCORD8T3y/c3G7ewKgR394t3H8efbFbzZGy4fpEXZ8yQ7dc0DIqBGNpv8K4ugCRcA/4wZNVKGHUKm/AqQQNJ8QBkVF8DYcijtttby5CaBXO/K1K8KOV0xF1tpYatGNBXGfGtBHfoGTwjV3RJdt4s2MXUdclLq7aN/6PweIpW9Hs4ONDIHCSjWjJpEsGPI8kPUbWvCDzTwrSr4LZR4ipxWNYXREj3Frp1de9fPQJaitY0iYy8Kj6ZWS0wd235OnEjjEtWjx8+HoD8febpVDI5V42JSwyPr4PNIG0bGq9YBn8SaqWzgepD8oBhuqDZxSKqfzfYD1gWlvfNmj5ML4zNJ3PAh2Qi3fxHZCJo791ZV+UQn2maapk/Y+3069fIinB36zEsjAzMQjlu6aYsmFikcHEPJo="
