name: Development
defaults:
  run:
    working-directory: code
on:
  pull_request:
    branches: 
      - 'development'
      - 'feature/dev-*'


jobs:
  verifying:
    name: Verifying
    runs-on: ubuntu-latest
    env:
      VARIANT_COMMAND_SUFFIX: Debug
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Assemble
        run: ./gradlew assemble$VARIANT_COMMAND_SUFFIX
      
      - name: Lint
        run: ./gradlew lint$VARIANT_COMMAND_SUFFIX
      
      - name: Test
        run: ./gradlew test$VARIANT_COMMAND_SUFFIX
      
      - name: Static Analysis
        run: ./gradlew sonarqube
