name: Production
defaults:
  run:
    working-directory: code
on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

env:
  VARIANT_COMMAND_SUFFIX: Acceptance
  VARIANT_NAME: acceptance


jobs:
  verifying:
    name: Verifying
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Assemble
        run: ./gradlew assemble$VARIANT_COMMAND_SUFFIX
      
      - name: Lint
        run: ./gradlew lint$VARIANT_COMMAND_SUFFIX
      
      - name: Test
        run: ./gradlew test$VARIANT_COMMAND_SUFFIX
      
      - name: Static Analysis
        run: ./gradlew sonarqube
  
  deploying:
    name: Deploying
    runs-on: ubuntu-latest
    needs: verifying
    env:
      DEPLOY_DIR_PATH: deployDir
      APP_NAME: pea-$GITHUB_WORKFLOW-$GITHUB_RUN_NUMBER.apk
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Assemble
        run: ./gradlew assemble$VARIANT_COMMAND_SUFFIX
      
      - name: Create Export Directory
        run: mkdir ../$DEPLOY_DIR_PATH
      
      - name: Moving App File
        run: mv app/build/outputs/apk/$VARIANT_NAME/app-$VARIANT_NAME.apk ../$DEPLOY_DIR_PATH/$APP_NAME
      
      - name: Compress Pro-Guard Logs
        run: tar -xcf ../$DEPLOY_DIR_PATH/proguard.tar.gz app/build/outputs/mapping
      
      - name: Archive APK
        uses: actions/upload-artifact@v1
        with:
          name: APK
          path: $DEPLOY_DIR_PATH/$APP_NAME
      
      - name: Archive Pro-Guard Logs
        uses: actions/upload-artifact@v1
        with:
          name: Pro-Guard Logs
          path: $DEPLOY_DIR_PATH/proguard.tar.fz
  
